Repository IRL2/nanover-server-py, pull requests merged in 2024-08, with the labels that each got.

#216 Add OpenMM tutorial notebooks
  examples/openmm/OpenMM runner.ipynb
  examples/openmm/images/nanover_nanotube.png
  examples/openmm/images/neuraminidase_ball_and_stick.png
  examples/openmm/images/neuraminidase_geometric_spline.png
  examples/openmm/nglclient.py
  examples/openmm/openmm_files/3TI6_ose_wt.rst
  examples/openmm/openmm_files/3TI6_ose_wt.top
  examples/openmm/openmm_files/nanotube.xml
  examples/openmm/openmm_nanotube.ipynb
  examples/openmm/openmm_neuraminidase.ipynb
  examples/openmm/openmm_polyalanine.ipynb
Labels: documentation, enhancement

#217 non-reporter omm
  python-libraries/nanover-omni/src/nanover/omni/openmm.py
Labels: Parity with rust

#219 Create getting_started.ipynb
  examples/fundamentals/getting_started.ipynb
Labels: documentation, enhancement

#228 Fix MDAnalysis force units when loading NanoVer trajectory as an MDAnalysis Universe
  python-libraries/nanover-mdanalysis/src/nanover/mdanalysis/universe.py
Labels: bug

#229 Update description of `OpenMMSimulation` class
  examples/openmm/openmm_polyalanine.ipynb
Labels: documentation

#226 Add MDAnalysis/NanoVer notebook for analysis of NanoVer recordings
  examples/mdanalysis/files/nanotube-recording.state
  examples/mdanalysis/files/nanotube-recording.traj
  examples/mdanalysis/mdanalysis_nanover_recording.ipynb
Labels: documentation, enhancement

#234 Update README
  README.md
Labels: documentation

#235 Fix broken links to Tutorials docs page in README
  README.md
Labels: documentation

#231 Add NGLClient to NanoVer as a module
  .github/workflows/conda.yml
  README.md
  examples/ase/__init__.py
  examples/ase/nanover_nglview.ipynb
  examples/ase/nglclient.py
  examples/ase/openmm_nanotube.ipynb
  examples/openmm/nglclient.py
  examples/openmm/openmm_nanotube.ipynb
  python-libraries/nanover-jupyter/conda/build.sh
  python-libraries/nanover-jupyter/conda/meta.yaml
  python-libraries/nanover-jupyter/setup.py
  python-libraries/nanover-jupyter/src/nanover/nglview/__init__.py
  python-libraries/nanover-jupyter/src/nanover/nglview/nglclient.py
  python-libraries/nanover-jupyter/src/nanover/nglview/py.typed
  python-libraries/nanover-server/conda/meta.yaml
Labels: enhancement

#237 Restructure fundamentals directory
  examples/ase/basic_example.ipynb
  examples/ase/openmm_nanotube.ipynb
  examples/basics/getting_started.ipynb
  examples/basics/nanover_nglview.ipynb
  examples/basics/openmm_files/nanotube.xml
  examples/lammps/lammps_client_server.ipynb
  examples/lammps/nglclient.py
Labels: documentation

#240 Fix DCD reporter section of example notebook
  examples/openmm/openmm_polyalanine.ipynb
Labels: documentation

#238 Add a notebook explaining recording and replaying in NanoVer
  examples/basics/getting_started.ipynb
  examples/basics/images/nanover_nanotube.png
  examples/basics/recording_and_replaying.ipynb
  examples/openmm/openmm_polyalanine.ipynb
Labels: documentation, enhancement
