Repository IRL2/nanover-server-py, pull requests merged in 2024-11, with the labels that each got.

#312 Update the notebooks based on recent repo name changes
  examples/ase/ase_openmm_nanotube.ipynb
  examples/basics/getting_started.ipynb
  examples/basics/recording_and_replaying.ipynb
  examples/fundamentals/frame.ipynb
  examples/fundamentals/servers.ipynb
  examples/fundamentals/visualisations.ipynb
  examples/mdanalysis/mdanalysis_lsd.ipynb
  examples/mdanalysis/mdanalysis_nanover_recording.ipynb
  examples/mdanalysis/mdanalysis_trajectory.ipynb
  examples/openmm/openmm_nanotube.ipynb
Labels: documentation

#314 Rework iMD in ASE
  python-libraries/nanover-ase/src/nanover/ase/converter.py
  python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py
  python-libraries/nanover-ase/tests/test_imd_calculator.py
  python-libraries/nanover-ase/tests/test_imd_reset.py
  python-libraries/nanover-omni/src/nanover/omni/ase.py
  python-libraries/nanover-omni/tests/test_ase.py
Labels: bug, enhancement

#318 Calculate user work done in `ASESimulation`
  python-libraries/nanover-core/src/nanover/imd/imd_force.py
  python-libraries/nanover-omni/src/nanover/omni/ase.py
  python-libraries/nanover-omni/src/nanover/omni/openmm.py
  python-libraries/nanover-omni/tests/test_ase.py
Labels: enhancement

#267 Added a Python GUI
  examples/basics/UI.py
  examples/basics/nanover_nglview.ipynb
  examples/basics/runner_GUI.ipynb
Labels: Parity with rust
